//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskWebApp.Models
{
    using System;
    using System.Collections.Generic;

    public enum TaskState
    {
        Waiting = 0,
        Continues = 1,
        Complete = 2
    }

    public partial class TasksData
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public TaskState State { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
    }
}
